name: hamara_shop
description: "A new Flutter project."


publish_to: 'none' 




version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'







dependencies:
  flutter:
    sdk: flutter


  # Utitlity Packages
  http: ^1.1.2
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.3.2
  smooth_page_indicator: ^1.1.0



  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2


  # State Management
  get: ^4.6.5
  get_storage: ^2.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter


  
  
  
  
  flutter_lints: ^2.0.0





flutter:
  assets:
    - assets/images/on_boarding_images/
    - assets/icons/
    - assets/logos/
    - assets/fonts/
    

  

  fonts:
    - family: Poopens
      fonts:
       - asset: assets/fonts/Poppins-Regular.ttf
         weight: 300
       - asset: assets/fonts/Rubik-Bold.ttf
         weight: 400
     
  
  
  
  uses-material-design: true
